import Head from "next/head";
import { PoolsPage } from "@/components/pages/pools";
import BondPage from "@/components/pages/pools/bond";

export default function Pools() {
  return (
    <div>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PoolsPage active="bond">
        <BondPage />
      </PoolsPage>
    </div>
  );
}
