import Head from "next/head";

import { PoolsPage } from "@/components/pages/pools";
import { PodStakingPage } from "@/components/pages/pools/podStaking";

export default function Pools() {
  return (
    <div>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PoolsPage active="pod-staking">
        <PodStakingPage />
      </PoolsPage>
    </div>
  );
}
