import Head from "next/head";
import { useRouter } from "next/router";
import { BreadCrumbs } from "@/components/UI/atoms/breadcrumbs";
import { Container } from "@/components/UI/atoms/container";
import { Hero } from "@/components/UI/molecules/Hero";
import { HeroTitle } from "@/components/UI/molecules/HeroTitle";
import { HeroStat } from "@/components/UI/molecules/HeroStat";
import { ClaimCxTokensTable } from "@/components/UI/organisms/my-policies/ClaimCxTokensTable";
import { useCoverInfo } from "@/components/pages/cover/useCoverInfo";
import { convertFromUnits } from "@/utils/bn";
import { formatAmount } from "@/utils/formatter";
import { toBytes32 } from "@/src/helpers/cover";
import { useActiveCoverPolicies } from "@/components/pages/my-policies/useActiveCoverPolicies";
import { useActivePolicies } from "@/components/pages/my-policies/useActivePolicies";

export default function ClaimPolicy() {
  const router = useRouter();
  const { cover_id } = router.query;
  const coverKey = toBytes32(cover_id);
  const { coverInfo } = useCoverInfo(coverKey);
  const { data } = useActiveCoverPolicies({ coverKey });
  const {
    data: { totalActiveProtection },
  } = useActivePolicies();

  const title = coverInfo?.projectName;

  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero>
        <Container className="px-2 py-20">
          <BreadCrumbs
            pages={[
              {
                name: "My Policies",
                href: "/my-policies/active",
                current: false,
              },
              { name: title, href: "#", current: false },
              { name: "Claim", href: "#", current: true },
            ]}
          />

          <div className="flex items-start">
            <HeroTitle>My Policies</HeroTitle>

            {/* My Active Protection */}
            <HeroStat title="My Active Protection">
              <>
                ${" "}
                {formatAmount(
                  convertFromUnits(totalActiveProtection).toString()
                )}
              </>
            </HeroStat>
          </div>
        </Container>

        <hr className="border-b border-B0C4DB" />
      </Hero>

      <Container className="px-2 pt-12 pb-36">
        <h2 className="text-h2 font-sora font-bold">
          Available cxTokens for {title} to Claim
        </h2>
        <p className="text-lg w-full pt-6 pb-16 lg:w-1/2 ml-0">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
        <ClaimCxTokensTable activePolicies={data.activePolicies} />
      </Container>
    </main>
  );
}
