import Head from "next/head";
import { useRouter } from "next/router";
import { useFetchReport } from "@/src/hooks/useFetchReport";
import { ReportingDetailsPage } from "@/components/pages/reporting/details";
import { toBytes32 } from "@/src/helpers/cover";

export default function IncidentResolvedCoverPage() {
  const router = useRouter();
  const { id: report_id_parsed, timestamp } = router.query;
  let report_id = toBytes32(report_id_parsed) + "-" + timestamp;

  const { data, loading } = useFetchReport(report_id);

  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {loading && <p className="text-center">Loading...</p>}

      {!data.incidentReport && <p className="text-center">No data found</p>}

      {data.incidentReport && (
        <ReportingDetailsPage incidentReport={data.incidentReport} />
      )}
    </main>
  );
}
