export const getPolicyTxs = () => [
  {
    timestamp: "few seconds ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purchased $250.000.45 Coinbase Policy",
    amountRecieved: "189,595.93",
    unit: "cxDAI",
    failed: false,
  },
  {
    timestamp: "4 Minutes ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purchased $3,256,350 OKEX Policy",
    amountRecieved: "2,154,355.34",
    unit: "cxDAI",
    failed: false,
  },
  {
    timestamp: "30 Minutes ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Claimed $33,418.33 Clearpool Policy",
    amountRecieved: "50,754.12",
    unit: "cxDAI",
    failed: true,
  },
  {
    timestamp: "13 hours ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purschased $250.000.45 Coinbase Policy",
    amountRecieved: "26,764.55",
    unit: "cxDAI",
    failed: false,
  },
  {
    timestamp: "a day ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purchased $299,999.8 Huobi Polciy",
    amountRecieved: "178,756.71",
    unit: "cxDAI",
    failed: false,
  },
  {
    timestamp: "a day ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purchased $299,999.8 Axie Infinity Policy",
    amountRecieved: "46,849.77",
    unit: "cxDAI",
    failed: false,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purchased $299,999.8 Hex Trust Policy",
    amountRecieved: "969,756.77",
    unit: "cxDAI",
    failed: false,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Claimed $299,999.8 Huobi Policy",
    amountRecieved: "46,849.77",
    unit: "cxDAI",
    failed: true,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purchased $299,999.8 Coinbase Policy",
    amountRecieved: "178,756.71",
    unit: "cxDAI",
    failed: false,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Purchased $299,999.8 OKEX Policy",
    amountRecieved: "178,756.71",
    unit: "cxDAI",
    failed: false,
  },
];
