import Head from "next/head";

export default function MyLiquidityCover() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>MyLiquidityCover</h1>
    </main>
  );
}
