import Head from "next/head";
import { MyLiquidityCheckoutPage } from "@/components/pages/my-liquidity/details";

export default function MyLiquidityCover() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <MyLiquidityCheckoutPage />
    </main>
  );
}
