import Head from "next/head";

import { CoverAddLiquidityCheckoutPage } from "@/components/pages/cover/add-liquidity/checkout";

export default function CoverAddLiquidityCheckout() {
  return (
    <>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoverAddLiquidityCheckoutPage />
    </>
  );
}
