import Head from "next/head";

import { CoverLiquidity } from "@/components/pages/cover/coverLiquidity";

export default function Cover() {
  return (
    <>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoverLiquidity />
    </>
  );
}
