import Head from "next/head";

import { CoverClaim } from "@/components/pages/cover/coverClaim";

export default function Cover() {
  return (
    <>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoverClaim />
    </>
  );
}
