import { Alert } from "@/components/UI/atoms/alert";
import { Checkbox } from "@/components/UI/atoms/checkbox";
import { Container } from "@/components/UI/atoms/container";
import { HlCalendar } from "@/lib/hl-calendar";
import Head from "next/head";

export default function Components() {
  const startDate = new Date();
  const endDate = new Date(startDate.getTime());
  endDate.setDate(startDate.getDate() + 6);

  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-F1F3F6 px-8 py-6">
        <form>
          <Checkbox id="checkid" name="checkinputname">
            I have read, understood, and agree to the terms of cover rules
          </Checkbox>
          <br />
          <button type="submit">submit</button>
        </form>

        <br />

        <Container>
          <Alert>
            <p>
              If you just came to know about a recent incident of Uniswap
              Exchange, carefully read the cover rules above. You can earn 20%
              of the minority fees if you are the first person to report this
              incident.
            </p>
          </Alert>
        </Container>

        <br />

        <div className="bg-white p-10">
          <HlCalendar startDate={startDate} endDate={endDate} />
        </div>
      </div>
    </main>
  );
}
