import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import FacebookIcon from "@/icons/facebook";
import LinkedinIcon from "@/icons/linkedin";
import TwitterIcon from "@/icons/twitter";

import { Container } from "@/components/layout/Container";
import { Grid } from "@/components/layout/Grid";

import { CoverCard } from "@/components/cover/card";
import { CoverActionCard } from "@/components/cover/action-card";
import { actions as coverActions } from "@/src/config/cover/actions";
import { ImageContainer } from "@/components/common/image-container";
import { OutlinedCard } from "@/components/common/outlined-card";
import { classNames } from "@/utils/classnames";

export default function Home() {
  const imgSrc = "/covers/clearpool.png";
  const title = "Clearpool";

  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-bg">
        {/* hero */}
        <div
          className="px-8 py-6"
          style={{
            backgroundImage: "url(/gradient.png)",
            backgroundSize: "cover",
            backgroundPosition: "left",
          }}
        >
          {/* Back button */}
          <button
            type="button"
            onClick={() => router.back()}
            className="text-primary py-3 px-4 border border-primary rounded-xl"
          >
            &#x27F5;&nbsp;Back
          </button>

          <div className="py-14">
            <Container>
              <div className="flex">
                <div>
                  <ImageContainer
                    size="md"
                    className="bg-ash-brand p-3 border border-ash-border mr-6"
                  >
                    <img
                      src={imgSrc}
                      alt={title}
                      className="inline-block max-w-full"
                    />
                  </ImageContainer>
                </div>
                <div>
                  <div className="flex items-center">
                    <h1 className="text-h2 font-sora font-bold">Clearpool</h1>
                    <div className="ml-4 rounded-full w-4 h-4 bg-teal-neutral"></div>
                  </div>
                  <p>
                    <a
                      href="https://clearpool.finance"
                      className="text-primary underline hover:no-underline"
                    >
                      clearpool.finance
                    </a>
                  </p>
                  <div className="mt-5">
                    <a
                      href="https://google.com"
                      className="inline-block mr-4 hover:text-primary"
                      target="_blank"
                    >
                      <FacebookIcon />
                    </a>
                    <a
                      href="https://google.com"
                      className="inline-block mr-4 hover:text-primary"
                      target="_blank"
                    >
                      <LinkedinIcon />
                    </a>
                    <a
                      href="https://google.com"
                      className="inline-block mr-4 hover:text-primary"
                      target="_blank"
                    >
                      <TwitterIcon />
                    </a>
                  </div>
                </div>
                <div className="ml-auto text-right">
                  <h5 className="font-sora text-h5">Total Liquidity</h5>
                  <p className="font-semibold text-primary text-h2">
                    5,234,759.00 DAI
                  </p>
                </div>
              </div>
            </Container>
          </div>
        </div>

        {/* Content */}
        <div className="pt-12 pb-24 border-t border-t-ash-border">
          <Container className="grid gap-32 grid-cols-3">
            <div className="col-span-2">
              {/* Description */}
              <p className="">
                Clearpool is a decentralized capital markets ecosystem where
                institutions can access uncollateralized liquidity. On the
                Clearpool app, institutional borrowers can make a proposal to be
                whitelisted by the Clearpool community - CPOOL token holders.
              </p>

              {/* Rules */}
              <h4 className="text-h4 font-sora font-semibold mt-10 mb-6">
                Cover Rules
              </h4>
              <p className="mb-4">
                Carefully read the following terms and conditions. For a
                successful claim payout, all of the following points must be
                true.
              </p>
              <ol className="list-decimal pl-5">
                <li>
                  From now till the claim expiry date of the cxTokens, you must
                  have maintained at least 25 NPM tokens in your wallet.
                </li>
                <li>
                  Before the claim expiry date of the cxTokens, the project was
                  hacked, resulting in more than $5M worth of cryptocurrency
                  being stolen.
                </li>
                <li>
                  The project did not announce, within 48 hours of the incident,
                  plan(s) to themselves cover at least 75% of the suffered loss.
                </li>
                <li>You did not transfer your cxToken to any other wallet.</li>
              </ol>

              {/* Accept Rules Form */}
              <form className="mt-20">
                <label className="p-1">
                  <input type="checkbox" checked /> I have read, understood, and
                  agree to the terms of cover rules
                </label>
                <br />
                <button
                  type="submit"
                  className={classNames(
                    true && "opacity-30 cursor-not-allowed",
                    "bg-primary text-white-fg py-3 px-4 mt-8 rounded-xl"
                  )}
                >
                  Next&nbsp;&#x27F6;
                </button>
              </form>
            </div>
            <div className="">
              <OutlinedCard className="bg-ash-brand p-10">
                <h3 className="text-h4 font-sora font-semibold">
                  Resolution Sources
                </h3>
                <p className="text-sm mt-1 mb-6 opacity-50">
                  7 days reporting period
                </p>

                <Link href="#">
                  <a className="block text-primary hover:underline mt-3">
                    Uniswap Knowledgebase
                  </a>
                </Link>

                <Link href="#">
                  <a className="block text-primary hover:underline mt-3">
                    Uniswap Twitter
                  </a>
                </Link>

                <hr className="mt-4 mb-6 border-t border-ash-border/60" />

                <div className="flex justify-between">
                  <span className="">Available Liquidity:</span>
                  <strong className="text-right font-bold">$ 750k</strong>
                </div>
              </OutlinedCard>
            </div>
          </Container>
        </div>

        {/* Cover Actions */}
        <div className="pt-20 pb-36 bg-ash-bg border-t border-t-ash-border">
          <Container>
            <h1 className="text-h2 font-sora font-bold mb-12 text-center">
              Didn’t Find What You Were Looking For?
            </h1>
            <Grid>
              {Object.keys(coverActions)
                // .filter((x) => x !== "purchase")
                .map((actionKey, i) => {
                  return (
                    <Link key={i} href={`/${actionKey}`}>
                      <a className="rounded-4xl focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-black focus:outline-none">
                        <CoverActionCard
                          title={coverActions[actionKey].title}
                          description={coverActions[actionKey].description}
                          imgSrc={`/cover-actions/${actionKey}.png`}
                        ></CoverActionCard>
                      </a>
                    </Link>
                  );
                })}
            </Grid>
          </Container>
        </div>
      </main>
    </div>
  );
}
