import Head from "next/head";
import CreateNewCoverPage from "../components/pages/cover/create/CreateNewCoverPage";

export default function CreateCover() {
  return (
    <>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <CreateNewCoverPage />
    </>
  );
}
