import Head from "next/head";

import { HomePage } from "@/components/pages/home";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage />
    </main>
  );
}
