import Head from "next/head";
import { CoverOptionsPage } from "@/components/pages/cover/CoverOptionsPage";

export default function Options() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <CoverOptionsPage />
    </main>
  );
}
