import Head from "next/head";

export default function ReportingNewCoverPage() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-8 py-6">{/*  */}</div>
    </main>
  );
}
