import { CreateNewIncidentPage } from "@/components/pages/reporting/create/create-new-incident";
import Head from "next/head";

export default function ReportingNewCoverPage() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CreateNewIncidentPage />
    </main>
  );
}
