import { useCoverInfo } from "@/components/pages/cover/useCoverInfo";
import { CoverReportingRules } from "@/components/reporting/CoverReportingRules";
import { NewIncidentReportForm } from "@/components/reporting/NewIncidentReportForm";
import { ReportingHero } from "@/components/UI/organisms/reporting/new/ReportingHero";
import { toBytes32 } from "@/src/helpers/cover";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function ReportingNewCoverPage() {
  const router = useRouter();
  const { cover_id } = router.query;
  const coverKey = toBytes32(cover_id);
  const { coverInfo } = useCoverInfo(coverKey);
  const [accepted, setAccepted] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [accepted]);

  if (!coverInfo) {
    return <>loading...</>;
  }

  const handleAcceptRules = () => {
    setAccepted(true);
  };

  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* hero */}
      <ReportingHero coverInfo={coverInfo} />

      {accepted ? (
        <NewIncidentReportForm />
      ) : (
        <CoverReportingRules
          coverInfo={coverInfo}
          handleAcceptRules={handleAcceptRules}
        />
      )}
    </main>
  );
}
