import Head from "next/head";
import { IncidentResolved } from "@/components/pages/reporting/incident/resolved";

export default function IncidentResolvedCoverPage() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <IncidentResolved />
    </main>
  );
}
