import Head from "next/head";

export default function ReportingVoteCoverPage() {
  return (
    <div>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-F1F3F6 px-8 py-6">
          {/*  */}
      </main>
    </div>
  );
}
