import Head from "next/head";
import { VotePage } from "@/components/pages/reporting/vote";

export default function ReportingVoteCoverPage() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VotePage />
    </main>
  );
}
