import Head from "next/head";
import { CoverReportingDetailsPage } from "@/components/pages/reporting/details/CoverReportingDetailsPage";

export default function ReportingNewCoverPage() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <CoverReportingDetailsPage />
    </main>
  );
}
