import Head from "next/head";
import { ReportingNewIncidentPage } from "@/components/pages/reporting/new/reporting-new-incident";

export default function ReportingNewCoverPage() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReportingNewIncidentPage />
    </main>
  );
}
