import Head from "next/head";

import { CoverReport } from "@/components/pages/cover/coverReport";

export default function CoverReportLanding() {
  return (
    <>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoverReport />
    </>
  );
}
