import Head from "next/head";
import { ReportingTabs } from "@/components/pages/reporting";
import { ReportingActivePage } from "@/components/pages/reporting/active";

export default function ReportingActive() {
  return (
    <div>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReportingTabs active="active">
        <ReportingActivePage />
      </ReportingTabs>
    </div>
  );
}
