import Head from "next/head";

import { CoverPurchaseCheckoutPage } from "@/components/pages/cover/purchase/checkout";

export default function CoverPurchaseCheckout() {
  return (
    <>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoverPurchaseCheckoutPage />
    </>
  );
}
