import Head from "next/head";
import { BreadCrumbs } from "@/components/UI/atoms/breadcrumbs";
import { Container } from "@/components/UI/atoms/container";
import { Hero } from "@/components/UI/molecules/Hero";
import { HeroTitle } from "@/components/UI/molecules/HeroTitle";
import { MyPoliciesTxsTable } from "@/components/UI/organisms/my-policies/MyPoliciesTxsTable";

export default function MyPoliciesTxs() {
  return (
    <main>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero>
        <Container className="px-2 py-20">
          <BreadCrumbs
            pages={[
              { name: "My Policies", href: "/my-policies", current: false },
              { name: "Transaction List", href: "#", current: true },
            ]}
          />

          <HeroTitle>Transaction List</HeroTitle>
        </Container>

        <hr className="border-b border-B0C4DB" />
      </Hero>

      <Container className="pt-14 pb-28">
        <p className="text-9B9B9B text-xs text-right font-semibold mb-8">
          LAST SYNCED: <span className="pl-1 text-4E7DD9">#265489098</span>
        </p>

        <MyPoliciesTxsTable />
      </Container>
    </main>
  );
}
