import Head from "next/head";
import { CoverId } from "@/components/pages/cover/coverId";

export default function Cover() {
  return (
    <>
      <Head>
        <title>Neptune Mutual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CoverId />
    </>
  );
}
