export const getLiquidityTxs = () => [
  {
    timestamp: "few seconds ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $250.000.45 to Coinbase",
    amountRecieved: "189,595.93",
    unit: "POD",
    failed: false,
  },
  {
    timestamp: "4 Minutes ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $3,256,350 to OKEX",
    amountRecieved: "2,154,355.34",
    unit: "POD",
    failed: false,
  },
  {
    timestamp: "30 Minutes ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Removed $33,418.33 from Clearpool",
    amountRecieved: "50,754.12",
    unit: "POD",
    failed: true,
  },
  {
    timestamp: "13 hours ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $250.000.45 to Coinbase",
    amountRecieved: "26,764.55",
    unit: "POD",
    failed: false,
  },
  {
    timestamp: "a day ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $299,999.8 Huobi Polciy",
    amountRecieved: "178,756.71",
    unit: "POD",
    failed: false,
  },
  {
    timestamp: "a day ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $299,999.8 Axie to Infinity",
    amountRecieved: "46,849.77",
    unit: "POD",
    failed: false,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $299,999.8 Hex to Trust",
    amountRecieved: "969,756.77",
    unit: "POD",
    failed: false,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Removed $299,999.8 from Huobi",
    amountRecieved: "46,849.77",
    unit: "POD",
    failed: true,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $299,999.8 to Coinbase",
    amountRecieved: "178,756.71",
    unit: "POD",
    failed: false,
  },
  {
    timestamp: "3 days ago",
    coverImgSrc: "/_mocks/icons/okex.png",
    info: "Added $299,999.8 to OKEX",
    amountRecieved: "178,756.71",
    unit: "POD",
    failed: false,
  },
];
